logging:
  level:
    .: error
    org.springframework: ERROR
    com.gmail: ERROR

spring:
  profiles:
    active: "local"

server:
  email: default@gmail.com

---

spring:
  profiles: local
server:
  email: local@gmail.com
---

spring:
  profiles: dev
server:
  email: dev@gmail.com
  
---

spring:
  profiles: staging
server:
  email: staging@gmail.com
---

spring:
  profiles: prod
server:
  email: prod@gmail.com
